spring:
  application:
      name: ai-agent
  ai:
    dashscope:
      api-key:  'sk-7318e9c2a4c5469cab68b63b0765fd69'
      chat:
        options:
          model: qwen-plus
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
  datasource:
    url: jdbc:postgresql://rm-cn-oqb4pgpzk0001m1o.rwlb.rds.aliyuncs.com:5432/ai_agent
    username: my_user
    password: Zsjr2468